spring:
  application:
    name: omnidocs-ai

  profiles:
    active: dev

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

      embedding:
        options:
          model: text-embedding-3-small