spring:
  application:
    name: omnidocs-ai

  profiles:
    active: dev

gemini:
  api-key: ${GEMINI_API_KEY}
  embedding-model: gemini-embedding-001
  chat-model: gemini-2.5-flash
  base-url: https://generativelanguage.googleapis.com