CREATE TABLE user_statistics
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    uuid UUID NOT NULL UNIQUE,

    user_id BIGINT NOT NULL UNIQUE,

    total_workspaces BIGINT NOT NULL DEFAULT 0,

    total_documents BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL,

    created_by VARCHAR(255),

    updated_at TIMESTAMP,

    updated_by VARCHAR(255),

    deleted BOOLEAN NOT NULL DEFAULT FALSE,

    deleted_at TIMESTAMP,

    deleted_by VARCHAR(255),

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_user_statistics_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
);

CREATE INDEX idx_user_statistics_uuid
    ON user_statistics(uuid);

CREATE INDEX idx_user_statistics_user
    ON user_statistics(user_id);