ALTER TABLE workspaces
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workspaces
ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE documents
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE documents
ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE stored_files
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE stored_files
ADD COLUMN deleted_at TIMESTAMP;